### ISSUE TITLE
feature request: Possibility to keep some descriptors in sPLS

### ISSUE THREAD

**Issue by lorenzoFabbri** [mixOmicsTeam/mixOmics#148]
Suppose I include some confounders in the matrix `X` of descriptors, and suppose also that I want to use sPLS. It would be important to have the possibility, like in `GLMNET`, to keep those variables *fixed* in all the models (e.g., to apply `keepX` to only a subset of the descriptors).

**Comment by aljabadi** [comment]
Hi @lorenzoFabbri,

While I can see the utility of such a feature for a limited case of studies, unfortunately, we cannot prioritise this feature in the near future. Contributions are most welcome though.

Thanks

Al

**Comment by Max-Bladen** [comment]
Hi @lorenzoFabbri,

I implemented this feature that you've requested but unfortunately it causes some issues. Namely, due to the way in which loadings are regularised, the user defined features to retain have their importance severely inflated. Hence, there isn't a way that we can think of currently which allows this functionality while also preserving the mathematical consistency of the function. If you are curious about the specifics, [look here](https://github.com/mixOmicsTeam/mixOmics/pull/220).

Here's the workaround: run a sPLS using all the features. From this, the optimal set of features will be yielded. Then, run a new PLS using all the yielded features from sPLS plus the ones you want to ensure are used.

I'll close this issue for now, but if we think of a way to sufficiently implement it I'll reopen the issue and inform you of such.

Cheers,
Max.
