### ISSUE TITLE
sPCA components in PlotIndiv both display as 0%

### ISSUE THREAD

**Issue by mirc66** [mixOmicsTeam/mixOmics#156]
------------
I am running R 4.1.0 in RStudio and  loaded mixOmics 6.16.3.  I am following the examples in  you Bookdown in section 3.7.1 there seems to be an error.  Instead of the plotIndv displaying with  PC1= 23% and PC2=17% both of these display as 0%.

When I check the output of  MyResult.spca: the results below dont seem to match what appears in Bookdown section 3.7.1

`> MyResult.spca
sparse PCA with 3 principal components. 
  Input data X of dimensions: 64 3116 
  Number of selected variables on each prinicipal components:
PC1   PC2   PC3   
 15    10     5   
  Proportion of adjusted explained variance for the first 3 principal components, see object$prop_expl_var: 
        PC1              PC2              PC3      
0.003856574      0.002213243      0.001108384      
  
 `

As per recommendations to other issues, i tried updating to the most current version (mixomix 6.17.28) from your GitHub via devtools.  Rather than fix the problem this caused other issues in that the PlotIndiv for PCA (Bookdown sec3.6.1 would only display colored dots rather than the labels no matter what i did including specifying where to get the  indiv.names.  

Since i need to use the indiv.names in the PCA I reverted back to mixOmics 6.16.3.   but still have the issue above
thanks

------------

**Comment by Max-Bladen** [comment]
Issue regarding proportion of explained variance as well as issue regarding sample names cannot be reproduced. Assuming the [commit 52292ef](https://github.com/aljabadi/mixOmics/commit/52292ef579200fb848a298490406e4368fcd7c69) resolved the former. 

Unclear about source of the error in the case of the latter. There are two potential causes based on comment by user:

1) They describe the use of the parameter `indiv.names`. Using this parameter has no effect and raises no error as the proper syntax is `ind.names`, not `indiv.names`.

2) If they were replicating the following code (from section 3.6.1 of the Bookdown):
```
plotIndiv(MyResult.pca, ind.names = TRUE,
          group = liver.toxicity$treatment$Dose.Group,
          pch = as.factor(liver.toxicity$treatment$Time.Group),
          legend = TRUE, title = 'Liver toxicity: genes, PCA comp 1 - 2',
          legend.title = 'Dose', legend.title.pch = 'Exposure')
````
This will not show the sample names as the `pch` parameter will overrides `ind.names` as to represent the time exposure of each sample with a symbol. Removing `pch` from the above call allows for control over whether the sample names are displayed or not.

Due to non-reproducibility of both errors, this issue will be closed.
