### ISSUE TITLE
Classification error rate (perf.diablo)

### ISSUE THREAD

**Issue by bariskkd** [mixOmicsTeam/mixOmics#28]
Hi,
 
When I try to assess global performance and choose the number of components, I'm getting high classification error rates between 0.4-0.55. Also, it is not decreasing by adding more components. What are the possible reasons and how can I solve this? Thank you for the help and package.

Best,

**Comment by mixOmicsTeam** [comment]
Hello @bariskkd 
There are *many* possible reasons to explain a poor prediction: 

- you don't have many samples (< 5 per group) and the model is overfitting

- you chose a wrong Mfold cross-validation so the model is trying to predict on too many samples. Let n = total number of samples, choose k (number of `folds`) such that n/k >= 5, otherwise use leave-one-out cross-validation `validation = "loo"`

- one (or more) dataset has poor predictive ability, it can be detected by running individual `plsda()` on each dataset, or with `plotDiablo() `after building a DIABLO model. If so, consider either changing the design argument in DIABLO (example given here: https://mixomicsteam.github.io/Bookdown/diablo.html#inputs-and-outputs-2) or removing datasets that are performing poorly (not ideal, but if really your goal is to do prediction ...

- alternatively, if all fails, you could stick to a descriptive or exploratory approach. Don't forget that we have the outputs from `perf()` called `stability` that will indicate what are the features that are repeatedly selected across the different CV folds. You can check the stability of the feature selection process, regardless of the classification performance.

Kim-Anh

**Comment by bariskkd** [comment]
Thanks for the suggestions @mixOmicsTeam,

I have 29 samples. I have tried Mfold cross validation with lower **"folds"** and **"loo"** cross-validation default "folds", but it didnot improve the prediction performance. I have checked predictive abilities of datasets with **plsda()**, error rates were still high in all. Then, I further reduce variables by choosing most significant differentially expressed ones, classification error rates were remarkably decreased. On the other hand, when I compare outputs from all variables and less variables, selected features were almost same. So,  classification performance may not reflect the inability in the following feature selection. 

Best,

**Comment by singha53-zz** [comment]
@bariskkd, please do not pre-filter variables with respect to class-labels:
"... I further reduce variables by choosing most significant differentially expressed ones, classification error rates were remarkably decreased."

see page 245 in [ESL](https://web.stanford.edu/~hastie/Papers/ESLII.pdf) for the right and wrong way to do cross-validation.

**Comment by bariskkd** [comment]
I see @singha53, but other filtering approaches didnot improve classification error rates. Last time, I have selected variables with highest variance as suggested at the end of page 246, classification error rates were still high and didnot go down with the increasing components. 
![Rplot1](https://user-images.githubusercontent.com/53220471/61853311-479ff880-aec4-11e9-821c-a9bc1879e6c5.png)

Used datasets are transcriptomic, miRNA and proteomic profilings of cancer cell lines  from CCLE.   

Best,

**Comment by singha53-zz** [comment]
Then it seems the signal might be too weak to develop a strong classifier (which is also good to know). Maybe try univariate testing instead and see if your p-value histogram is positively skewed?
http://varianceexplained.org/statistics/interpreting-pvalue-histogram/

@bariskkd sorry for the late reply

**Comment by mixOmicsTeam** [comment]
Hi @bariskkd,
from our discussions, it seems that your data may not be amenable for classification with our tools, or that some datasets are really not great to classify your samples on (see perhaps the function plotDiablo to diagnose this). 
The fact that the error rate increases when you add more components mean that more noise (selected variables on Component 2 and onwards) enter and decrease classification ability. 

I am closing this issue as I believe for now, we have given you several options to investigate. Feel free to contact us later on if you have additional questions.
