### ISSUE TITLE
Is mixOmics still being supported? 

### ISSUE THREAD

**Issue by topepo** [mixOmicsTeam/mixOmics#301]
One of our packages depends on it and we just received: 

> Dear maintainer,
>
> Please see the problems shown on <https://www.google.com/url?q=https://cran.r-project.org/web/checks/check_results_plsmod.html&source=gmail-imap&ust=1698685798000000&usg=AOvVaw3xoGAatbwjqL_qEqyvWlbu>.
>
> The errors currently seen for r-devel are from switching to Bioconductor 3.18 (which will be released in the next few days).  The same switch was recently made for r-patched and hence will also make it into R 4.3.2 to be released on Oct 31.
>
> Bioconductor 3.18 is currently missing package mixOmics, as this shows check errors, see 
>
> <https://www.google.com/url?q=https://bioconductor.org/checkResults/3.18/bioc-LATEST/mixOmics&source=gmail-imap&ust=1698685798000000&usg=AOvVaw0BZ1MuCvoCqRjkp9WvEm8P>
>
> The maintainer has apparently been unresponsive, to likely the BioC team will look into formally deprecating mixOmics following the 3.18 release. However, with mixOmics missing your package is currently uninstallable, so action on your end is required.
>
> Can you please fix "as necessary"?  I.e., either change your package to at best suggest mixOmics (and use it conditionally), or ensure that mixOmics gets fixed.  Perhaps you would be interested in picking up maintenance if the current mixOmics maintainer continues to not respond? In that case, contact <mailto:devteam-bioc@bioconductor.org>.
>
> Please correct before 2023-11-06 to safely retain your package on CRAN.

**Comment by evaham1** [comment]
Hi @topepo, sorry for the delayed response, mixOmics has been without a maintainer for the last few months which is why we have not been responsive over this period. However I have recently started as the new maintainer so this will change! :) mixOmics now runs on R4.4 and has passed Bioconductor checks so will be released at the end of the month with Bioconductor 3.20 

https://bioconductor.org/checkResults/3.20/bioc-LATEST/mixOmics/
