### ISSUE TITLE
keep order of the X variables when plotting loadings from a pls-da model?

### ISSUE THREAD

**Issue by meireles** [mixOmicsTeam/mixOmics#48]
I would really like to have the option to keep the order of the covariates in the X matrix when using `plotLoadings`. Currently, the variables seem to be sorted by order of importance.

**Comment by aljabadi** [comment]
Hi @meireles,

Thanks for using mixOmics. 
It is in fact possible to save the output from `plotLoadings` and get the `data.frame` used to create the barplot with all the plot specs as you wish (you can get the whole function in RStudio using `mixOmics::plotLoadings.mixo_splsda` - no parentheses). Because this is the first time we have had such a request and we have limited resources, you're more than welcome to suggest changes through a pull request for the benefit of other users.

Hope it helps.
Al

**Comment by meireles** [comment]
@ajabadi Thanks, that helps a lot!
