### ISSUE TITLE
installing the mixOmics package

### ISSUE THREAD

**Issue by felixcactus** [mixOmicsTeam/mixOmics#55]
Hi, I am trying to run PLS-DA on my data and have been stuck getting the mixOmics library loaded. I have R 3.6.1 running on OS. I used the following script to install the mixOmics package:

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("mixOmics")

when I then try to load the library for mixOmics, I get the following error:

Error: package or namespace load failed for ‘mixOmics’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘RSpectra’

when I try to install.packages("RSpectra") separately, I get the following message on repeat:

In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/unsupported/Eigen/SparseExtra:51:
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include/unsupported/Eigen/../../Eigen/src/Core/util/ReenableStupidWarnings.h:10:30: warning: pragma diagnostic pop could not pop, no matching push [-Wunknown-pragmas]
    #pragma clang diagnostic pop

What can I do to load get the mixOmics library loaded?

**Comment by aljabadi** [comment]
Hi @felixcactu,

Does the problem persist when you install the GitHub version using https://github.com/mixOmicsTeam/mixOmics#latest-github-version?

**Comment by felixcactus** [comment]
I did use the github version and the problem persists. But I do see that mixOmics  and BiocManager packages are installed. I just can't get the the mixOmics library to load without error messages.

**Comment by aljabadi** [comment]
Hi @felixcactus,

Unfortunately, this is an issue that occurs with Rcpp packages (which mixOmics does not depend on) and is not a mixOmics issue. You can try the following:
### 1.remove RcppEigen

```r
remove.package("RcppEigen")
```

### 2. restart R

### 3. re-install RcppEigen
```r
options("install.packages.compile.from.source"="no")
install.packages("RcppEigen", dependencies=TRUE)
```

### 4. load mixOmics

If this failed, see what happens if you remove RcppEigen and try to load only mixOmics. You can see more [here](https://stackoverflow.com/questions/56094213/how-do-i-fix-package-or-namespace-load-failed). I'm closing this but please let us know how you go.
